try:
    x = 4
except:
  print("An exception occurred")

print(x)